root: /shops/html/
admin_dir: admin/
tpl: /shops/html/user_data/packages/default/
admin_tpl: /shops/html/user_data/packages/admin/
image_path: /shops/html/upload/save_image/
root_dir: C:\xampp\htdocs\shops
root_urlpath: /shops/
template_code: '3002'
admin_route: admin
user_data_route: user_data
public_path: /html
public_path_realdir: C:\xampp\htdocs\shops/html
image_save_realdir: C:\xampp\htdocs\shops/html/upload/save_image
image_temp_realdir: C:\xampp\htdocs\shops/html/upload/temp_image
user_data_realdir: C:\xampp\htdocs\shops/html/user_data
block_default_realdir: C:\xampp\htdocs\shops/src/Eccube/Resource/template/default/Block
block_realdir: C:\xampp\htdocs\shops/app/template/default/Block
template_default_realdir: C:\xampp\htdocs\shops/src/Eccube/Resource/template/default
template_default_html_realdir: C:\xampp\htdocs\shops/html/template/default
template_admin_realdir: C:\xampp\htdocs\shops/src/Eccube/Resource/template/admin
template_admin_html_realdir: C:\xampp\htdocs\shops/html/template/admin
template_realdir: C:\xampp\htdocs\shops/app/template/3002
template_html_realdir: C:\xampp\htdocs\shops/html/template/3002
template_temp_realdir: C:\xampp\htdocs\shops/app/cache/eccube/template
csv_temp_realdir: C:\xampp\htdocs\shops/app/cache/eccube/csv
plugin_realdir: C:\xampp\htdocs\shops/app/Plugin
plugin_temp_realdir: C:\xampp\htdocs\shops/app/cache/plugin
plugin_html_realdir: C:\xampp\htdocs\shops/html/plugin
admin_urlpath: /shops/html/template/admin
front_urlpath: /shops/app/template/3002
image_save_urlpath: /shops/html/upload/save_image
image_temp_urlpath: /shops/html/upload/temp_image
user_data_urlpath: /shops/html/user_data
plugin_urlpath: /shops/html/plugin
