<?php

namespace Plugin\DPost\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CustomerExRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomerExRepository extends EntityRepository
{
    public $app;

    public function setApplication($app) {
        $this->app = $app;
    }

    public function getRegistList() {

        $qb = $this->createQueryBuilder('cex')
                ->innerJoin('\Eccube\Entity\Customer', 'c', 'WITH', 'cex.customer_id = c.id')
                ->where('c.del_flg = 0 and cex.regist_id is not null');

        return $qb->getQuery()->getResult();
    }

    public function getRegistIdCount($regist_id) {

        $qb = $this->createQueryBuilder('cex')
                ->select('count(cex.customerExId)')
                ->where('cex.regist_id = :regist_id')
                ->setParameter(':regist_id', $regist_id);

        return $qb->getQuery()->getSingleScalarResult();
    }
}
