<?php

namespace Plugin\DPost\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PostQueueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostQueueRepository extends EntityRepository
{
    public $app;

    public function setApplication($app) {
        $this->app = $app;
    }

    public function getClickCount($news_id) {

        $qb = $this->createQueryBuilder('pq')
                ->select('count(pq.post_id)')
                ->where('pq.queue_status = 2 and pq.news_id = :news_id')
                ->setParameter(':news_id', $news_id);

        return $qb->getQuery()->getSingleScalarResult();
    }
}
