<?php

namespace Plugin\DPost\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProductPushRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductPushRepository extends EntityRepository
{
}
