<?php
/*
 * Copyright(c) 2015 Telecom and Et Payment Gateway, Inc. All rights reserved.
 */

namespace Plugin\ExternalPaymentGateway\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query;

/**
 * PaymentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExternalPaymentMethodRepository extends EntityRepository
{

    /**
     * @var array array of configs
     */
    private $config;

    /**
     * Set the config of this repository
     * @param array $config
     */
    public function setConfig(array $config)
    {
        $this->config = $config;
    }

    /**
     * Find or create payment method
     *
     * @param type $id
     * @return type
     */
    public function findOrCreate($id)
    {
        if ($id == 0) {
            $Payment = new \Plugin\ExternalPaymentGateway\Entity\ExternalPaymentMethod();
            $Payment
                ->setDelFlg(0)
                ->setUpdateDate('CURRENT_TIMESTAMP')
                ->setCreateDate('CURRENT_TIMESTAMP');
        } else {
            $Payment = $this->find($id);
        }

        return $Payment;
    }

    /**
     * find all
     *
     * @return type
     */
    public function findAllArray()
    {

        $query = $this
            ->getEntityManager()
            ->createQuery('SELECT p FROM Eccube\Entity\Payment p INDEX BY p.id');
        $result = $query
            ->getResult(Query::HYDRATE_ARRAY);

        return $result;
    }

    /**
     * Get all payment_id of table dtb_payment base on plugin_code of table plg_external_payment_method
     *
     * @param bool $incDel Flag for counting deleted record
     * @return array()
     */
    public function getPaymentByCode($incDel,$app)
    {
        $softDeleteFilter = $app['orm.em']->getFilters()->getFilter('soft_delete');
        $originExcludes = $softDeleteFilter->getExcludes();

        if ($incDel){
            $softDeleteFilter->setExcludes(array(
                'Eccube\Entity\Payment',
                'Plugin\ExternalPaymentGateway\Entity\ExternalPaymentMethod'
            )); 
        }
        

        $qb = $this->getEntityManager()->createQueryBuilder();
        $qb
            ->select('p.id')
            ->from('\Eccube\Entity\Payment', 'p')
            ->innerJoin('\Plugin\ExternalPaymentGateway\Entity\ExternalPaymentMethod', 'g', 'WITH', 'p.id = g.id')
            ->where($qb->expr()->andx(                
                $qb->expr()->eq('g.code', ':code'))
            );
        $qb->setParameter('code', $this->config['EXTERNAL_CREDIT_CODE']);
        
        $ret = $qb
            ->getQuery()
            ->getResult();
        
        if ($incDel){
            $softDeleteFilter->setExcludes($originExcludes);
        }
        
        return $ret;
        
        
    }

    /**
     * Get payment by type, with option to including or excluding deleted record
     *
     * @param type $paymentTypeId
     * @param type $app
     * @return type
     */
    public function getPaymentByType($paymentTypeId, $incDel, $app)
    {
        $softDeleteFilter = $app['orm.em']->getFilters()->getFilter('soft_delete');
        $originExcludes = $softDeleteFilter->getExcludes();
            
        if ($incDel){
            $softDeleteFilter->setExcludes(array(
                'Eccube\Entity\Payment',
                'Plugin\ExternalPaymentGateway\Entity\ExternalPaymentMethod'
            )); 
        }
        
        $qb = $this->getEntityManager()->createQueryBuilder();
        $qb
            ->select('p')
            ->from('\Eccube\Entity\Payment', 'p')
            ->join('\Plugin\ExternalPaymentGateway\Entity\ExternalPaymentMethod', 'g', 'WITH', 'p.id = g.id')
            ->where(
                $qb->expr()->eq('g.memo03', ':x')
            );
        $qb->setParameter('x', $paymentTypeId);
        
        $ret = $qb
            ->getQuery()
            ->setMaxResults(1)
            ->getOneOrNullResult();
        
        if ($incDel){
            $softDeleteFilter->setExcludes($originExcludes);
        }
        
        return $ret;
    }
    
    public function getExternalPayment($field, $value, $incDel, $app){
        $softDeleteFilter = $app['orm.em']->getFilters()->getFilter('soft_delete');
        $originExcludes = $softDeleteFilter->getExcludes();
            
        if ($incDel){
            $softDeleteFilter->setExcludes(array(
                'Plugin\ExternalPaymentGateway\Entity\ExternalPaymentMethod'
            )); 
        }
        
        $ExternalPayment = $app['eccube.plugin.external_pg.repository.external_payment_method']->findOneBy(array($field => $value));
        
        if ($incDel){
            $softDeleteFilter->setExcludes($originExcludes);
        }
        
        return $ExternalPayment;
        
    }

    /**
     * Delete payment
     *
     * @param type $paymentId
     * @return boolean
     */
    public function deletePayment($paymentId)
    {
        $qb = $this->getEntityManager()->createQueryBuilder();
        $qb
            ->select('p')
            ->from('\Eccube\Entity\Payment', 'p')
            ->where($qb->expr()->andx(
                $qb->expr()->eq('p.del_flg', 0),
                $qb->expr()->eq('p.id', ':id'))
            );
        $qb->setParameter('id', $paymentId);

        try {
            $Payment = $qb
                ->getQuery()
                ->setMaxResults(1)
                ->getSingleResult();

        } catch (\Exception $e) {
            return false;
        }

        $em = $this->getEntityManager();
        $em->remove($Payment);
        $em->flush();

        return true;
    }

}
